# Generated by Django 3.2 on 2022-09-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.TextField()),
                ('remarks', models.TextField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('material_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_db_mgr.material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_db_mgr.unit')),
            ],
        ),
    ]
