# Generated by Django 3.2 on 2022-09-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_db_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
